function findAddedLetter(s: string, t: string): string {
    let sCharCount: { [key: string]: number } = {};
    let tCharCount: { [key: string]: number } = {};

    for (let i = 0; i < s.length; i++) {
        sCharCount[s[i]] = (sCharCount[s[i]] || 0) + 1;
    }

    for (let i = 0; i < t.length; i++) {
        tCharCount[t[i]] = (tCharCount[t[i]] || 0) + 1;
    }

    for (let key in tCharCount) {
        if (sCharCount[key] !== tCharCount[key]) {
            return key;
        }
    }

    return '';
}

/*
question: You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 
Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.


Example 2:

Input: s = "", t = "y"
Output: "y"


 
Constraints:


	0 <= s.length <= 1000
	t.length == s.length + 1
	s and t consist of lowercase English letters.

 */
