name: Random Daily Runs

on:
  schedule:
    - cron: '0 9 * * *' # Trigger the workflow daily at 9 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  random-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config user.name "gary-rivera"
          git config user.email "a.gary.rivera@gmail.com"

      - name: Generate random number of runs
        id: random
        run: |
          # Generate a random number between 2 and 8
          COUNT=$(( (RANDOM % 7) + 2 ))
          echo "COUNT=$COUNT" >> $GITHUB_ENV
          echo "Randomly selected $COUNT runs for today."

      - name: Run Vacay script
        run: npx ts-node scripts/vacay.ts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LC_CSRF_TOKEN: ${{ secrets.LC_CSRF_TOKEN }}
          LC_SESSION: ${{ secrets.LC_SESSION }}

      - name: Execute additional runs with unique sleep intervals
        run: |
          for i in $(seq 2 $COUNT); do
            echo "Run #$i of $COUNT"
            # Generate a random sleep interval between 30 and 90 minutes
            DELAY=$(( (RANDOM % 61) + 30 ))
            echo "Sleeping for $DELAY minutes..."
            sleep $((DELAY * 60)) # Convert minutes to seconds
            npx ts-node scripts/vacay.ts
          done
        env:
          COUNT: ${{ env.COUNT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LC_CSRF_TOKEN: ${{ secrets.LC_CSRF_TOKEN }}
          LC_SESSION: ${{ secrets.LC_SESSION }}

      - name: Commit and push solutions
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add solutions
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add new solutions"
            git push
          fi
