name: Daily Run @ 20 UTC

on:
  schedule:
    - cron: '11 20 * * *' # Daily at 12:11PM PST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  script-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: 50% Chance of Execution
        id: chance
        run: |
          #!/bin/bash
          # Generate a random number between 0 and 1
          RANDOM_NUMBER=$(( RANDOM % 2 ))
          if [ $RANDOM_NUMBER -ne 0 ]; then
            echo "skip=true" >> $GITHUB_ENV
            echo "Skipping execution due to 50% chance condition."
          else
            echo "skip=false" >> $GITHUB_ENV
            echo "Proceeding with execution."
          fi

      - name: Debug Environment Variable
        run: echo "skip=$skip"

      - name: Set up Node.js
        if: env.skip == 'false'
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        if: env.skip == 'false'
        run: npm install

      - name: Configure Git
        if: env.skip == 'false'
        run: |
          git config user.name "gary-rivera"
          git config user.email "a.gary.rivera@gmail.com"

      - name: Random delay before execution
        if: env.skip == 'false'
        run: |
          #!/bin/bash
          DELAY=$(( RANDOM % 601 ))
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY

      - name: Run Vacay script (Single Execution)
        if: env.skip == 'false'
        run: npx ts-node scripts/vacay.ts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LC_CSRF_TOKEN: ${{ secrets.LC_CSRF_TOKEN }}
          LC_SESSION: ${{ secrets.LC_SESSION }}

      - name: Commit and push solutions
        if: env.skip == 'false'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull --rebase
          git add solutions
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add new solutions"
            git push
          fi
