name: Daily Run @ 17 UTC

on:
  schedule:
    - cron: '0 17 * * *' #Daily at 9 AM PST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  script-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config user.name "gary-rivera"
          git config user.email "a.gary.rivera@gmail.com"

      - name: Random delay before execution
        run: |
          # Generate a random delay between 0 and 600 seconds (10 minutes)
          DELAY=$(( RANDOM % 601 ))
          echo "Sleeping for $DELAY seconds..."
          sleep $DELAY

      - name: Run Vacay script (Single Execution)
        run: npx ts-node scripts/vacay.ts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LC_CSRF_TOKEN: ${{ secrets.LC_CSRF_TOKEN }}
          LC_SESSION: ${{ secrets.LC_SESSION }}

      - name: Commit and push solutions
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull --rebase
          git add solutions
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add new solutions"
            git push
          fi
